- name: Install Ruby
  hosts: all
  become: true
  tasks:
    - pause: seconds=20
    - name: Update repositories cache and install packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - ruby-full
        - ruby-bundler
        - build-essential
